# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: George Oikonomou
email: g.oikonomou@bristol.ac.uk
description: George Oikonomou's home page.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with
  <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url: https://spd.gr # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Allow links to the page to be displayed with a preview object on social media
# To achieve this, change serve_og_meta to true and then provide a URL for
# og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: g-oikonomou # your GitHub user name
twitter_username: oikonomou_geo # your Twitter handle
linkedin_username: georgeoikonomou # your LinkedIn user name
scholar_userid: oLr89jwAAAAJ # your Google Scholar ID
orcid_id: 0000-0002-1684-6989 # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: 1365681 # your ID on Publons
research_gate_profile: George_Oikonomou # your profile on ResearchGate
blogger_url: http://blog.spd.gr # your blogger URL

contact_note: >
  The best way to contact me is by email.

google_analytics: # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: al-folio
blog_description: a simple whitespace theme for academics
blog_display: false

# Pagination
#paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: false
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /pubs/:path/

news_limit: 5
pubs_url: /pubs/type
# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor, bin]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Oikonomou

  style: ieee
  locale: en

  sort_by: year
  order: descending

  source: /assets/bib/
  bibliography: geo.bib
  bibliography_template: geo_bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
